---
- name: installing and running nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started

- name: installing git 
  hosts: git 
  become: yes
  tasks:
  - name: install git
    ansible.builtin.yum:
      name: git
      state: present