---
- name:
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages 
    ansible.builtin.yum:
    - name: {{item}} 
      state: present
    loop:
    - mongodb
    - nginx
    - postfix
    - mysql
    - git